### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [WildEgor/WildEgor.github.io#1]
1. Прогоните все `png` через https://tinypng.com/
2. У ссылок в хедере должны быть хотя бы псевдоссылки на `#`, а лучше на реальные секции макета
3. https://github.com/WildEgor/WildEgor.github.io/blob/ac10c16ddef9cd108a2cdb62d9e1412417a6aecc/SF/index.html#L180 https://github.com/WildEgor/WildEgor.github.io/blob/ac10c16ddef9cd108a2cdb62d9e1412417a6aecc/SF/index.html#L390 Это не кнопки
4. https://github.com/WildEgor/WildEgor.github.io/blob/ac10c16ddef9cd108a2cdb62d9e1412417a6aecc/SF/style/components/fantasies.css#L3 https://github.com/WildEgor/WildEgor.github.io/blob/ac10c16ddef9cd108a2cdb62d9e1412417a6aecc/SF/style/components/questions.css#L2 Неверные пути
5. На 1024 и 768 верстка разваливается

**Comment by WildEgor** [comment]
Исправил все что вы написали
[https://github.com/WildEgor/WildEgor.github.io/commit/d1adeca1f1da7d81cb5e79f47593d4a102adaddd](url)

и немного поправил вид при <320px:
[https://github.com/WildEgor/WildEgor.github.io/commit/d1adeca1f1da7d81cb5e79f47593d4a102adaddd](url)
